// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StationeryPlus.Server.Data;

#nullable disable

namespace StationeryPlus.Server.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("StationeryPlus.Shared.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageURL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Price")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "HB Pencils, Superior hb bonded, lead resists breakage, Clear and sharp writing",
                            ImageURL = "https://m.media-amazon.com/images/I/71lOR49VkwL._SL1500_.jpg",
                            Price = 80,
                            Title = "Nataraj 621 Pencils"
                        },
                        new
                        {
                            Id = 2,
                            Description = "HB Pencils, Superior hb bonded, lead resists breakage, Clear and sharp writing",
                            ImageURL = "https://m.media-amazon.com/images/I/71lOR49VkwL._SL1500_.jpg",
                            Price = 80,
                            Title = "Nataraj 621 Pencils"
                        },
                        new
                        {
                            Id = 3,
                            Description = "HB Pencils, Superior hb bonded, lead resists breakage, Clear and sharp writing",
                            ImageURL = "https://m.media-amazon.com/images/I/71lOR49VkwL._SL1500_.jpg",
                            Price = 80,
                            Title = "Nataraj 621 Pencils"
                        },
                        new
                        {
                            Id = 4,
                            Description = "HB Pencils, Superior hb bonded, lead resists breakage, Clear and sharp writing",
                            ImageURL = "https://m.media-amazon.com/images/I/71lOR49VkwL._SL1500_.jpg",
                            Price = 80,
                            Title = "Nataraj 621 Pencils"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
